/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.10.1.0 (NJsonSchema v10.3.3.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class CustomerClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    addOrUpdateCustomer(customer?: CustomerViewModel | null | undefined): Observable<CustomerViewModel | null> {
        let url_ = this.baseUrl + "/api/Customer/AddOrUpdateCustomer";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(customer);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAddOrUpdateCustomer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAddOrUpdateCustomer(<any>response_);
                } catch (e) {
                    return <Observable<CustomerViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<CustomerViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processAddOrUpdateCustomer(response: HttpResponseBase): Observable<CustomerViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? CustomerViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CustomerViewModel | null>(<any>null);
    }

    addOrUpdateTenant(tenant?: TenantViewModel | null | undefined): Observable<TenantViewModel | null> {
        let url_ = this.baseUrl + "/api/Customer/AddOrUpdateTenant";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(tenant);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAddOrUpdateTenant(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAddOrUpdateTenant(<any>response_);
                } catch (e) {
                    return <Observable<TenantViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<TenantViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processAddOrUpdateTenant(response: HttpResponseBase): Observable<TenantViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? TenantViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<TenantViewModel | null>(<any>null);
    }

    deleteTenant(deleteTenant?: DeleteTenantViewModel | null | undefined): Observable<DeleteTenantViewModel | null> {
        let url_ = this.baseUrl + "/api/Customer/DeleteTenant";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(deleteTenant);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDeleteTenant(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDeleteTenant(<any>response_);
                } catch (e) {
                    return <Observable<DeleteTenantViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<DeleteTenantViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processDeleteTenant(response: HttpResponseBase): Observable<DeleteTenantViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? DeleteTenantViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<DeleteTenantViewModel | null>(<any>null);
    }

    getCustomer(): Observable<CustomerViewModel | null> {
        let url_ = this.baseUrl + "/api/Customer/GetCustomer";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCustomer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCustomer(<any>response_);
                } catch (e) {
                    return <Observable<CustomerViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<CustomerViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetCustomer(response: HttpResponseBase): Observable<CustomerViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? CustomerViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<CustomerViewModel | null>(<any>null);
    }

    getCustomerId(): Observable<number | null> {
        let url_ = this.baseUrl + "/api/Customer/GetCustomerId";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetCustomerId(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetCustomerId(<any>response_);
                } catch (e) {
                    return <Observable<number | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<number | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetCustomerId(response: HttpResponseBase): Observable<number | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number | null>(<any>null);
    }

    getNewAssignmentKey(): Observable<string> {
        let url_ = this.baseUrl + "/api/Customer/GetNewAssignmentKey";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetNewAssignmentKey(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetNewAssignmentKey(<any>response_);
                } catch (e) {
                    return <Observable<string>><any>_observableThrow(e);
                }
            } else
                return <Observable<string>><any>_observableThrow(response_);
        }));
    }

    protected processGetNewAssignmentKey(response: HttpResponseBase): Observable<string> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<string>(<any>null);
    }

    getTenantsForCustomer(): Observable<TenantViewModel[] | null> {
        let url_ = this.baseUrl + "/api/Customer/GetTenantsForCustomer";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTenantsForCustomer(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTenantsForCustomer(<any>response_);
                } catch (e) {
                    return <Observable<TenantViewModel[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<TenantViewModel[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetTenantsForCustomer(response: HttpResponseBase): Observable<TenantViewModel[] | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TenantViewModel.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<TenantViewModel[] | null>(<any>null);
    }
}

@Injectable()
export class EmployeeClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    addOrUpdateEmployee(employee?: EmployeeViewModel | null | undefined): Observable<EmployeeViewModel | null> {
        let url_ = this.baseUrl + "/api/Employee/AddOrUpdateEmployee";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(employee);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processAddOrUpdateEmployee(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processAddOrUpdateEmployee(<any>response_);
                } catch (e) {
                    return <Observable<EmployeeViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<EmployeeViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processAddOrUpdateEmployee(response: HttpResponseBase): Observable<EmployeeViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? EmployeeViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<EmployeeViewModel | null>(<any>null);
    }

    getEmployee(): Observable<EmployeeViewModel | null> {
        let url_ = this.baseUrl + "/api/Employee/GetEmployee";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetEmployee(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetEmployee(<any>response_);
                } catch (e) {
                    return <Observable<EmployeeViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<EmployeeViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetEmployee(response: HttpResponseBase): Observable<EmployeeViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? EmployeeViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<EmployeeViewModel | null>(<any>null);
    }
}

@Injectable()
export class Client {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    _configuration(clientId: string): Observable<FileResponse | null> {
        let url_ = this.baseUrl + "/_configuration/{clientId}";
        if (clientId === undefined || clientId === null)
            throw new Error("The parameter 'clientId' must be defined.");
        url_ = url_.replace("{clientId}", encodeURIComponent("" + clientId));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.process_configuration(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.process_configuration(<any>response_);
                } catch (e) {
                    return <Observable<FileResponse | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<FileResponse | null>><any>_observableThrow(response_);
        }));
    }

    protected process_configuration(response: HttpResponseBase): Observable<FileResponse | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return _observableOf({ fileName: fileName, data: <any>responseBlob, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<FileResponse | null>(<any>null);
    }
}

@Injectable()
export class TenantClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getHasTenantAccess(tenantId: number): Observable<boolean> {
        let url_ = this.baseUrl + "/api/Tenant/GetHasTenantAccess?";
        if (tenantId === undefined || tenantId === null)
            throw new Error("The parameter 'tenantId' must be defined and cannot be null.");
        else
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetHasTenantAccess(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetHasTenantAccess(<any>response_);
                } catch (e) {
                    return <Observable<boolean>><any>_observableThrow(e);
                }
            } else
                return <Observable<boolean>><any>_observableThrow(response_);
        }));
    }

    protected processGetHasTenantAccess(response: HttpResponseBase): Observable<boolean> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<boolean>(<any>null);
    }

    getTenantIdFromAssignmentKey(assignmentKey: string): Observable<number> {
        let url_ = this.baseUrl + "/api/Tenant/GetTenantIdFromAssignmentKey?";
        if (assignmentKey === undefined || assignmentKey === null)
            throw new Error("The parameter 'assignmentKey' must be defined and cannot be null.");
        else
            url_ += "assignmentKey=" + encodeURIComponent("" + assignmentKey) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTenantIdFromAssignmentKey(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTenantIdFromAssignmentKey(<any>response_);
                } catch (e) {
                    return <Observable<number>><any>_observableThrow(e);
                }
            } else
                return <Observable<number>><any>_observableThrow(response_);
        }));
    }

    protected processGetTenantIdFromAssignmentKey(response: HttpResponseBase): Observable<number> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number>(<any>null);
    }

    getTenantIdFromSlug(slug: string | null): Observable<number> {
        let url_ = this.baseUrl + "/api/Tenant/GetTenantIdFromSlug?";
        if (slug === undefined)
            throw new Error("The parameter 'slug' must be defined.");
        else if(slug !== null)
            url_ += "slug=" + encodeURIComponent("" + slug) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTenantIdFromSlug(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTenantIdFromSlug(<any>response_);
                } catch (e) {
                    return <Observable<number>><any>_observableThrow(e);
                }
            } else
                return <Observable<number>><any>_observableThrow(response_);
        }));
    }

    protected processGetTenantIdFromSlug(response: HttpResponseBase): Observable<number> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<number>(<any>null);
    }

    getTenant(tenantId: number): Observable<TenantViewModel | null> {
        let url_ = this.baseUrl + "/api/Tenant/GetTenant?";
        if (tenantId === undefined || tenantId === null)
            throw new Error("The parameter 'tenantId' must be defined and cannot be null.");
        else
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTenant(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTenant(<any>response_);
                } catch (e) {
                    return <Observable<TenantViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<TenantViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetTenant(response: HttpResponseBase): Observable<TenantViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? TenantViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<TenantViewModel | null>(<any>null);
    }
}

@Injectable()
export class TestClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    testApplicationLayerException(): Observable<FileResponse | null> {
        let url_ = this.baseUrl + "/api/Test/TestApplicationLayerException";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTestApplicationLayerException(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTestApplicationLayerException(<any>response_);
                } catch (e) {
                    return <Observable<FileResponse | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<FileResponse | null>><any>_observableThrow(response_);
        }));
    }

    protected processTestApplicationLayerException(response: HttpResponseBase): Observable<FileResponse | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return _observableOf({ fileName: fileName, data: <any>responseBlob, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<FileResponse | null>(<any>null);
    }

    testAuthorizationException(): Observable<FileResponse | null> {
        let url_ = this.baseUrl + "/api/Test/TestAuthorizationException";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTestAuthorizationException(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTestAuthorizationException(<any>response_);
                } catch (e) {
                    return <Observable<FileResponse | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<FileResponse | null>><any>_observableThrow(response_);
        }));
    }

    protected processTestAuthorizationException(response: HttpResponseBase): Observable<FileResponse | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return _observableOf({ fileName: fileName, data: <any>responseBlob, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<FileResponse | null>(<any>null);
    }

    testNotFoundException(): Observable<FileResponse | null> {
        let url_ = this.baseUrl + "/api/Test/TestNotFoundException";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTestNotFoundException(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTestNotFoundException(<any>response_);
                } catch (e) {
                    return <Observable<FileResponse | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<FileResponse | null>><any>_observableThrow(response_);
        }));
    }

    protected processTestNotFoundException(response: HttpResponseBase): Observable<FileResponse | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return _observableOf({ fileName: fileName, data: <any>responseBlob, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<FileResponse | null>(<any>null);
    }

    testInvalidOperationException(): Observable<FileResponse | null> {
        let url_ = this.baseUrl + "/api/Test/TestInvalidOperationException";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTestInvalidOperationException(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTestInvalidOperationException(<any>response_);
                } catch (e) {
                    return <Observable<FileResponse | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<FileResponse | null>><any>_observableThrow(response_);
        }));
    }

    protected processTestInvalidOperationException(response: HttpResponseBase): Observable<FileResponse | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            const fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
            const fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            return _observableOf({ fileName: fileName, data: <any>responseBlob, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<FileResponse | null>(<any>null);
    }
}

@Injectable()
export class TimeOffClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getPaidTimeOffPolicyDetail(id: number, tenantId: number): Observable<GetPaidTimeOffPolicyDetailViewModel | null> {
        let url_ = this.baseUrl + "/api/TimeOff/GetPaidTimeOffPolicyDetail?";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined and cannot be null.");
        else
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        if (tenantId === undefined || tenantId === null)
            throw new Error("The parameter 'tenantId' must be defined and cannot be null.");
        else
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPaidTimeOffPolicyDetail(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPaidTimeOffPolicyDetail(<any>response_);
                } catch (e) {
                    return <Observable<GetPaidTimeOffPolicyDetailViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GetPaidTimeOffPolicyDetailViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetPaidTimeOffPolicyDetail(response: HttpResponseBase): Observable<GetPaidTimeOffPolicyDetailViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GetPaidTimeOffPolicyDetailViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GetPaidTimeOffPolicyDetailViewModel | null>(<any>null);
    }

    getPaidTimeOffPolicyList(tenantId: number): Observable<GetPaidTimeOffPolicyListViewModel[] | null> {
        let url_ = this.baseUrl + "/api/TimeOff/GetPaidTimeOffPolicyList?";
        if (tenantId === undefined || tenantId === null)
            throw new Error("The parameter 'tenantId' must be defined and cannot be null.");
        else
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPaidTimeOffPolicyList(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPaidTimeOffPolicyList(<any>response_);
                } catch (e) {
                    return <Observable<GetPaidTimeOffPolicyListViewModel[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GetPaidTimeOffPolicyListViewModel[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetPaidTimeOffPolicyList(response: HttpResponseBase): Observable<GetPaidTimeOffPolicyListViewModel[] | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GetPaidTimeOffPolicyListViewModel.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GetPaidTimeOffPolicyListViewModel[] | null>(<any>null);
    }

    validateRequestedPaidTimeOffHours(request?: ValidateRequestedPaidTimeOffHoursViewModel | null | undefined): Observable<PaidTimeOffRequestValidationResult> {
        let url_ = this.baseUrl + "/api/TimeOff/ValidateRequestedPaidTimeOffHours";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processValidateRequestedPaidTimeOffHours(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processValidateRequestedPaidTimeOffHours(<any>response_);
                } catch (e) {
                    return <Observable<PaidTimeOffRequestValidationResult>><any>_observableThrow(e);
                }
            } else
                return <Observable<PaidTimeOffRequestValidationResult>><any>_observableThrow(response_);
        }));
    }

    protected processValidateRequestedPaidTimeOffHours(response: HttpResponseBase): Observable<PaidTimeOffRequestValidationResult> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PaidTimeOffRequestValidationResult>(<any>null);
    }

    getPaidTimeOffRequestsForEmployee(employeeId: number | null, tenantId: number): Observable<PaidTimeOffRequestViewModel[] | null> {
        let url_ = this.baseUrl + "/api/TimeOff/GetPaidTimeOffRequestsForEmployee?";
        if (employeeId === undefined)
            throw new Error("The parameter 'employeeId' must be defined.");
        else if(employeeId !== null)
            url_ += "employeeId=" + encodeURIComponent("" + employeeId) + "&";
        if (tenantId === undefined || tenantId === null)
            throw new Error("The parameter 'tenantId' must be defined and cannot be null.");
        else
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPaidTimeOffRequestsForEmployee(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPaidTimeOffRequestsForEmployee(<any>response_);
                } catch (e) {
                    return <Observable<PaidTimeOffRequestViewModel[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<PaidTimeOffRequestViewModel[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetPaidTimeOffRequestsForEmployee(response: HttpResponseBase): Observable<PaidTimeOffRequestViewModel[] | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PaidTimeOffRequestViewModel.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PaidTimeOffRequestViewModel[] | null>(<any>null);
    }

    getPaidTimeOffRequestsForTenant(tenantId: number): Observable<PaidTimeOffRequestViewModel[] | null> {
        let url_ = this.baseUrl + "/api/TimeOff/GetPaidTimeOffRequestsForTenant?";
        if (tenantId === undefined || tenantId === null)
            throw new Error("The parameter 'tenantId' must be defined and cannot be null.");
        else
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetPaidTimeOffRequestsForTenant(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetPaidTimeOffRequestsForTenant(<any>response_);
                } catch (e) {
                    return <Observable<PaidTimeOffRequestViewModel[] | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<PaidTimeOffRequestViewModel[] | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetPaidTimeOffRequestsForTenant(response: HttpResponseBase): Observable<PaidTimeOffRequestViewModel[] | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(PaidTimeOffRequestViewModel.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<PaidTimeOffRequestViewModel[] | null>(<any>null);
    }

    submitNewPaidTimeOffRequest(request?: SubmitNewPaidTimeOffRequestViewModel | null | undefined): Observable<SubmitNewPaidTimeOffRequestViewModel | null> {
        let url_ = this.baseUrl + "/api/TimeOff/SubmitNewPaidTimeOffRequest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSubmitNewPaidTimeOffRequest(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSubmitNewPaidTimeOffRequest(<any>response_);
                } catch (e) {
                    return <Observable<SubmitNewPaidTimeOffRequestViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<SubmitNewPaidTimeOffRequestViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processSubmitNewPaidTimeOffRequest(response: HttpResponseBase): Observable<SubmitNewPaidTimeOffRequestViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? SubmitNewPaidTimeOffRequestViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<SubmitNewPaidTimeOffRequestViewModel | null>(<any>null);
    }
}

@Injectable()
export class UserClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }

    getUserStatus(tenantId: number | null): Observable<UserStatusViewModel | null> {
        let url_ = this.baseUrl + "/api/User/GetUserStatus?";
        if (tenantId === undefined)
            throw new Error("The parameter 'tenantId' must be defined.");
        else if(tenantId !== null)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetUserStatus(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetUserStatus(<any>response_);
                } catch (e) {
                    return <Observable<UserStatusViewModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<UserStatusViewModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetUserStatus(response: HttpResponseBase): Observable<UserStatusViewModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? UserStatusViewModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<UserStatusViewModel | null>(<any>null);
    }
}

export class CustomerViewModel implements ICustomerViewModel {
    address1!: string;
    address2?: string | undefined;
    city!: string;
    companyName!: string;
    currencyCode!: string;
    firstName!: string;
    lastName!: string;
    middleName?: string | undefined;
    state!: string;
    title?: Title | undefined;
    zipCode!: string;

    constructor(data?: ICustomerViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.address1 = _data["address1"];
            this.address2 = _data["address2"];
            this.city = _data["city"];
            this.companyName = _data["companyName"];
            this.currencyCode = _data["currencyCode"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.middleName = _data["middleName"];
            this.state = _data["state"];
            this.title = _data["title"];
            this.zipCode = _data["zipCode"];
        }
    }

    static fromJS(data: any): CustomerViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new CustomerViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["address1"] = this.address1;
        data["address2"] = this.address2;
        data["city"] = this.city;
        data["companyName"] = this.companyName;
        data["currencyCode"] = this.currencyCode;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["middleName"] = this.middleName;
        data["state"] = this.state;
        data["title"] = this.title;
        data["zipCode"] = this.zipCode;
        return data; 
    }
}

export interface ICustomerViewModel {
    address1: string;
    address2?: string | undefined;
    city: string;
    companyName: string;
    currencyCode: string;
    firstName: string;
    lastName: string;
    middleName?: string | undefined;
    state: string;
    title?: Title | undefined;
    zipCode: string;
}

export enum Title {
    Mr = 0,
    Miss = 1,
    Mrs = 2,
    Ms = 3,
}

export class TenantViewModel implements ITenantViewModel {
    assignmentKey!: string;
    id!: number;
    name!: string;
    slug!: string;

    constructor(data?: ITenantViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.assignmentKey = _data["assignmentKey"];
            this.id = _data["id"];
            this.name = _data["name"];
            this.slug = _data["slug"];
        }
    }

    static fromJS(data: any): TenantViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new TenantViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["assignmentKey"] = this.assignmentKey;
        data["id"] = this.id;
        data["name"] = this.name;
        data["slug"] = this.slug;
        return data; 
    }
}

export interface ITenantViewModel {
    assignmentKey: string;
    id: number;
    name: string;
    slug: string;
}

export class DeleteTenantViewModel implements IDeleteTenantViewModel {
    confirmationCode!: string;
    tenantId!: number;

    constructor(data?: IDeleteTenantViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.confirmationCode = _data["confirmationCode"];
            this.tenantId = _data["tenantId"];
        }
    }

    static fromJS(data: any): DeleteTenantViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new DeleteTenantViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["confirmationCode"] = this.confirmationCode;
        data["tenantId"] = this.tenantId;
        return data; 
    }
}

export interface IDeleteTenantViewModel {
    confirmationCode: string;
    tenantId: number;
}

export class EmployeeViewModel implements IEmployeeViewModel {
    address1!: string;
    address2?: string | undefined;
    assignmentKey!: string;
    city!: string;
    currencyCode!: string;
    dateTerminated?: Date | undefined;
    dateHired!: Date;
    dateOfBirth!: Date;
    employeeLevel!: number;
    externalEmployeeId?: string | undefined;
    firstName!: string;
    gender!: Gender;
    id!: number;
    lastName!: string;
    managerId?: number | undefined;
    middleName?: string | undefined;
    paidTimeOffPolicyId!: number;
    ptoHoursRemaining?: number | undefined;
    salary!: number;
    socialSecurityNumber!: string;
    state!: string;
    subordinateIds!: number[];
    tenantId!: number;
    zipCode!: string;

    constructor(data?: IEmployeeViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.subordinateIds = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.address1 = _data["address1"];
            this.address2 = _data["address2"];
            this.assignmentKey = _data["assignmentKey"];
            this.city = _data["city"];
            this.currencyCode = _data["currencyCode"];
            this.dateTerminated = _data["dateTerminated"] ? new Date(_data["dateTerminated"].toString()) : <any>undefined;
            this.dateHired = _data["dateHired"] ? new Date(_data["dateHired"].toString()) : <any>undefined;
            this.dateOfBirth = _data["dateOfBirth"] ? new Date(_data["dateOfBirth"].toString()) : <any>undefined;
            this.employeeLevel = _data["employeeLevel"];
            this.externalEmployeeId = _data["externalEmployeeId"];
            this.firstName = _data["firstName"];
            this.gender = _data["gender"];
            this.id = _data["id"];
            this.lastName = _data["lastName"];
            this.managerId = _data["managerId"];
            this.middleName = _data["middleName"];
            this.paidTimeOffPolicyId = _data["paidTimeOffPolicyId"];
            this.ptoHoursRemaining = _data["ptoHoursRemaining"];
            this.salary = _data["salary"];
            this.socialSecurityNumber = _data["socialSecurityNumber"];
            this.state = _data["state"];
            if (Array.isArray(_data["subordinateIds"])) {
                this.subordinateIds = [] as any;
                for (let item of _data["subordinateIds"])
                    this.subordinateIds!.push(item);
            }
            this.tenantId = _data["tenantId"];
            this.zipCode = _data["zipCode"];
        }
    }

    static fromJS(data: any): EmployeeViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new EmployeeViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["address1"] = this.address1;
        data["address2"] = this.address2;
        data["assignmentKey"] = this.assignmentKey;
        data["city"] = this.city;
        data["currencyCode"] = this.currencyCode;
        data["dateTerminated"] = this.dateTerminated ? this.dateTerminated.toISOString() : <any>undefined;
        data["dateHired"] = this.dateHired ? this.dateHired.toISOString() : <any>undefined;
        data["dateOfBirth"] = this.dateOfBirth ? this.dateOfBirth.toISOString() : <any>undefined;
        data["employeeLevel"] = this.employeeLevel;
        data["externalEmployeeId"] = this.externalEmployeeId;
        data["firstName"] = this.firstName;
        data["gender"] = this.gender;
        data["id"] = this.id;
        data["lastName"] = this.lastName;
        data["managerId"] = this.managerId;
        data["middleName"] = this.middleName;
        data["paidTimeOffPolicyId"] = this.paidTimeOffPolicyId;
        data["ptoHoursRemaining"] = this.ptoHoursRemaining;
        data["salary"] = this.salary;
        data["socialSecurityNumber"] = this.socialSecurityNumber;
        data["state"] = this.state;
        if (Array.isArray(this.subordinateIds)) {
            data["subordinateIds"] = [];
            for (let item of this.subordinateIds)
                data["subordinateIds"].push(item);
        }
        data["tenantId"] = this.tenantId;
        data["zipCode"] = this.zipCode;
        return data; 
    }
}

export interface IEmployeeViewModel {
    address1: string;
    address2?: string | undefined;
    assignmentKey: string;
    city: string;
    currencyCode: string;
    dateTerminated?: Date | undefined;
    dateHired: Date;
    dateOfBirth: Date;
    employeeLevel: number;
    externalEmployeeId?: string | undefined;
    firstName: string;
    gender: Gender;
    id: number;
    lastName: string;
    managerId?: number | undefined;
    middleName?: string | undefined;
    paidTimeOffPolicyId: number;
    ptoHoursRemaining?: number | undefined;
    salary: number;
    socialSecurityNumber: string;
    state: string;
    subordinateIds: number[];
    tenantId: number;
    zipCode: string;
}

export enum Gender {
    Male = 0,
    Female = 1,
}

export class GetPaidTimeOffPolicyDetailViewModel implements IGetPaidTimeOffPolicyDetailViewModel {
    allowsUnlimitedPto!: boolean;
    employeeLevel!: number;
    id!: number;
    isDefaultForEmployeeLevel!: boolean;
    maxPtoHours?: number | undefined;
    name!: string;
    ptoAccrualRate?: number | undefined;

    constructor(data?: IGetPaidTimeOffPolicyDetailViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.allowsUnlimitedPto = _data["allowsUnlimitedPto"];
            this.employeeLevel = _data["employeeLevel"];
            this.id = _data["id"];
            this.isDefaultForEmployeeLevel = _data["isDefaultForEmployeeLevel"];
            this.maxPtoHours = _data["maxPtoHours"];
            this.name = _data["name"];
            this.ptoAccrualRate = _data["ptoAccrualRate"];
        }
    }

    static fromJS(data: any): GetPaidTimeOffPolicyDetailViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new GetPaidTimeOffPolicyDetailViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["allowsUnlimitedPto"] = this.allowsUnlimitedPto;
        data["employeeLevel"] = this.employeeLevel;
        data["id"] = this.id;
        data["isDefaultForEmployeeLevel"] = this.isDefaultForEmployeeLevel;
        data["maxPtoHours"] = this.maxPtoHours;
        data["name"] = this.name;
        data["ptoAccrualRate"] = this.ptoAccrualRate;
        return data; 
    }
}

export interface IGetPaidTimeOffPolicyDetailViewModel {
    allowsUnlimitedPto: boolean;
    employeeLevel: number;
    id: number;
    isDefaultForEmployeeLevel: boolean;
    maxPtoHours?: number | undefined;
    name: string;
    ptoAccrualRate?: number | undefined;
}

export class GetPaidTimeOffPolicyListViewModel implements IGetPaidTimeOffPolicyListViewModel {
    allowsUnlimitedPto!: boolean;
    employeeLevel!: number;
    id!: number;
    isDefaultForEmployeeLevel!: boolean;
    name!: string;

    constructor(data?: IGetPaidTimeOffPolicyListViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.allowsUnlimitedPto = _data["allowsUnlimitedPto"];
            this.employeeLevel = _data["employeeLevel"];
            this.id = _data["id"];
            this.isDefaultForEmployeeLevel = _data["isDefaultForEmployeeLevel"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): GetPaidTimeOffPolicyListViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new GetPaidTimeOffPolicyListViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["allowsUnlimitedPto"] = this.allowsUnlimitedPto;
        data["employeeLevel"] = this.employeeLevel;
        data["id"] = this.id;
        data["isDefaultForEmployeeLevel"] = this.isDefaultForEmployeeLevel;
        data["name"] = this.name;
        return data; 
    }
}

export interface IGetPaidTimeOffPolicyListViewModel {
    allowsUnlimitedPto: boolean;
    employeeLevel: number;
    id: number;
    isDefaultForEmployeeLevel: boolean;
    name: string;
}

export enum PaidTimeOffRequestValidationResult {
    NotEnoughHours = 0,
    OverlapsWithExisting = 1,
    InThePast = 2,
    TooFarInTheFuture = 3,
    StartDateAfterEndDate = 4,
    OK = 5,
}

export class ValidateRequestedPaidTimeOffHoursViewModel implements IValidateRequestedPaidTimeOffHoursViewModel {
    forEmployeeId!: number;
    hoursRequested!: number;
    endDate!: Date;
    startDate!: Date;
    tenantId!: number;

    constructor(data?: IValidateRequestedPaidTimeOffHoursViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.forEmployeeId = _data["forEmployeeId"];
            this.hoursRequested = _data["hoursRequested"];
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : <any>undefined;
            this.tenantId = _data["tenantId"];
        }
    }

    static fromJS(data: any): ValidateRequestedPaidTimeOffHoursViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new ValidateRequestedPaidTimeOffHoursViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["forEmployeeId"] = this.forEmployeeId;
        data["hoursRequested"] = this.hoursRequested;
        data["endDate"] = this.endDate ? this.endDate.toISOString() : <any>undefined;
        data["startDate"] = this.startDate ? this.startDate.toISOString() : <any>undefined;
        data["tenantId"] = this.tenantId;
        return data; 
    }
}

export interface IValidateRequestedPaidTimeOffHoursViewModel {
    forEmployeeId: number;
    hoursRequested: number;
    endDate: Date;
    startDate: Date;
    tenantId: number;
}

export class PaidTimeOffRequestViewModel implements IPaidTimeOffRequestViewModel {
    approvalStatus!: PaidTimeOffRequestApprovalStatus;
    status!: PaidTimeOffRequestStatus;
    endDate!: Date;
    forEmployeeId!: number;
    forEmployeeName!: string;
    hoursRequested!: number;
    id!: number;
    notes?: string | undefined;
    startDate!: Date;
    paid!: boolean;
    submittedById!: number;
    submittedByName!: string;

    constructor(data?: IPaidTimeOffRequestViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.approvalStatus = _data["approvalStatus"];
            this.status = _data["status"];
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.forEmployeeId = _data["forEmployeeId"];
            this.forEmployeeName = _data["forEmployeeName"];
            this.hoursRequested = _data["hoursRequested"];
            this.id = _data["id"];
            this.notes = _data["notes"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : <any>undefined;
            this.paid = _data["paid"];
            this.submittedById = _data["submittedById"];
            this.submittedByName = _data["submittedByName"];
        }
    }

    static fromJS(data: any): PaidTimeOffRequestViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new PaidTimeOffRequestViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["approvalStatus"] = this.approvalStatus;
        data["status"] = this.status;
        data["endDate"] = this.endDate ? this.endDate.toISOString() : <any>undefined;
        data["forEmployeeId"] = this.forEmployeeId;
        data["forEmployeeName"] = this.forEmployeeName;
        data["hoursRequested"] = this.hoursRequested;
        data["id"] = this.id;
        data["notes"] = this.notes;
        data["startDate"] = this.startDate ? this.startDate.toISOString() : <any>undefined;
        data["paid"] = this.paid;
        data["submittedById"] = this.submittedById;
        data["submittedByName"] = this.submittedByName;
        return data; 
    }
}

export interface IPaidTimeOffRequestViewModel {
    approvalStatus: PaidTimeOffRequestApprovalStatus;
    status: PaidTimeOffRequestStatus;
    endDate: Date;
    forEmployeeId: number;
    forEmployeeName: string;
    hoursRequested: number;
    id: number;
    notes?: string | undefined;
    startDate: Date;
    paid: boolean;
    submittedById: number;
    submittedByName: string;
}

export enum PaidTimeOffRequestApprovalStatus {
    Submitted = 0,
    Approved = 1,
    Canceled = 2,
    Rejected = 3,
    Invalid = 4,
}

export enum PaidTimeOffRequestStatus {
    Pending = 0,
    Taken = 1,
    Canceled = 2,
}

export class SubmitNewPaidTimeOffRequestViewModel implements ISubmitNewPaidTimeOffRequestViewModel {
    endDate!: Date;
    forEmployeeId?: number | undefined;
    hoursRequested!: number;
    result!: PaidTimeOffRequestValidationResult;
    startDate!: Date;
    createdPaidTimeOffRequest?: PaidTimeOffRequestViewModel | undefined;
    tenantId!: number;

    constructor(data?: ISubmitNewPaidTimeOffRequestViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : <any>undefined;
            this.forEmployeeId = _data["forEmployeeId"];
            this.hoursRequested = _data["hoursRequested"];
            this.result = _data["result"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : <any>undefined;
            this.createdPaidTimeOffRequest = _data["createdPaidTimeOffRequest"] ? PaidTimeOffRequestViewModel.fromJS(_data["createdPaidTimeOffRequest"]) : <any>undefined;
            this.tenantId = _data["tenantId"];
        }
    }

    static fromJS(data: any): SubmitNewPaidTimeOffRequestViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new SubmitNewPaidTimeOffRequestViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["endDate"] = this.endDate ? this.endDate.toISOString() : <any>undefined;
        data["forEmployeeId"] = this.forEmployeeId;
        data["hoursRequested"] = this.hoursRequested;
        data["result"] = this.result;
        data["startDate"] = this.startDate ? this.startDate.toISOString() : <any>undefined;
        data["createdPaidTimeOffRequest"] = this.createdPaidTimeOffRequest ? this.createdPaidTimeOffRequest.toJSON() : <any>undefined;
        data["tenantId"] = this.tenantId;
        return data; 
    }
}

export interface ISubmitNewPaidTimeOffRequestViewModel {
    endDate: Date;
    forEmployeeId?: number | undefined;
    hoursRequested: number;
    result: PaidTimeOffRequestValidationResult;
    startDate: Date;
    createdPaidTimeOffRequest?: PaidTimeOffRequestViewModel | undefined;
    tenantId: number;
}

export class UserStatusViewModel implements IUserStatusViewModel {
    authorizedTenants!: number[];
    hasProvidedCustomerInformation!: boolean;
    hasProvidedEmployeeInformation!: boolean;
    isCustomer!: boolean;

    constructor(data?: IUserStatusViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.authorizedTenants = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["authorizedTenants"])) {
                this.authorizedTenants = [] as any;
                for (let item of _data["authorizedTenants"])
                    this.authorizedTenants!.push(item);
            }
            this.hasProvidedCustomerInformation = _data["hasProvidedCustomerInformation"];
            this.hasProvidedEmployeeInformation = _data["hasProvidedEmployeeInformation"];
            this.isCustomer = _data["isCustomer"];
        }
    }

    static fromJS(data: any): UserStatusViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new UserStatusViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.authorizedTenants)) {
            data["authorizedTenants"] = [];
            for (let item of this.authorizedTenants)
                data["authorizedTenants"].push(item);
        }
        data["hasProvidedCustomerInformation"] = this.hasProvidedCustomerInformation;
        data["hasProvidedEmployeeInformation"] = this.hasProvidedEmployeeInformation;
        data["isCustomer"] = this.isCustomer;
        return data; 
    }
}

export interface IUserStatusViewModel {
    authorizedTenants: number[];
    hasProvidedCustomerInformation: boolean;
    hasProvidedEmployeeInformation: boolean;
    isCustomer: boolean;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}